# This is a basic workflow to help you get started with Actions

name: pull_request_opened
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: 
  pull_request:
    types: [ opened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Start test1 workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: start-test1
      if: ${{ steps.branch.outputs.name }} == "feature1_new_title"
    - name: Start test2 workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKENN }}
        event-type: start-test2
      if: ${{ steps.branch.outputs.name }} == "feature2_short_description"
    - name: Start test3 workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: start-test3
      if: ${{ steps.branch.outputs.name }} == "feature3_character_traits"   
    - name: Start test4 workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: start-test4
      if: ${{ steps.branch.outputs.name }} == "feature4_quote"  
    - name: Start test5 workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: start-test5
      if: ${{ steps.branch.outputs.name }} == "feature5_image"
   
